### ISSUE TITLE
When evaluating the trained model, hard_label number dimension error exists

### ISSUE THREAD

**Issue by ghost** [marmoi/dcase2023_task4b_baseline#3]
In evaluate.py,  [eval_meta] function makes error. The erroneous line is "event_classes=config.labels_hard"

If I change it to "event_classes=config.labels_soft", it doesn't have any error.

Where should I change?

**Comment by marmoi** [comment]
Thanks for spotting this, it was a mistake, I have updated evaluation functions for the hard labels, and added a funtion to save the soft labels as well.
