### ISSUE TITLE
FileNotFoundError: File path not correct

### ISSUE THREAD

**Issue by tanmayy24** [marmoi/dcase2023_task4b_baseline#4]
1. The path for the wav files in the development_split.csv should contain '/' instead of '\\'.
This is creating this error: 
FileNotFoundError: [Errno 2] No such file or directory: 'data/audio/cafe_restaurant\\cafe_restaurant_07.wav'

2. The function extract_data saves .npz files using filename instead of audioname, but when we run the fold_normalization function, it looks for audio name to load the .npz file. 
Creating this error:
FileNotFoundError: [Errno 2] No such file or directory: 'features_mbe/grocery_store_01.npz'

3. Similarly, the function merge_annotations_into_folds also tries to load .npz using the audio name. 
Creating this error:
FileNotFoundError: [Errno 2] No such file or directory: 'features_mbe/grocery_store_01_soft.npz'

This can be fixed at once by changing the path '/' instead of '\\' in the development_split.csv

**Comment by marmoi** [comment]
Thank you for spotting this, the development_split.csv file has been updated.
