### ISSUE TITLE
What is the correct baseline for F1MO?

### ISSUE THREAD

**Issue by v-nhandt21** [marmoi/dcase2023_task4b_baseline#5]
In the DCASE task4B
![image](https://user-images.githubusercontent.com/36092323/234324514-cbfce603-871a-4b36-b290-042078b72aee.png)

while in this repo, the F1MO is only 42

![image](https://user-images.githubusercontent.com/36092323/234324878-da4ef89f-7764-4e2b-9386-716e9dce1d16.png)

**Comment by marmoi** [comment]
Hi,
The one in the repo is correct. The web page will be updated soon to add this value and also for eval data results.
I apologize for the confusion
