### ISSUE TITLE
How to calculate F1MO？

### ISSUE THREAD

**Issue by WangMY5** [marmoi/dcase2023_task4b_baseline#6]
The results reported on DCASE's website have four indicators, as follows:
![image](https://github.com/marmoi/dcase2023_task4b_baseline/assets/109084633/b2e742b4-2f60-4425-acd1-eecf79c42625)
When I was running the code, the final result only showed Micro-average ER, F1 and Macro-average F1M, without the result of F1MO. 
![image](https://github.com/marmoi/dcase2023_task4b_baseline/assets/109084633/a3b2e8db-77f0-4856-91cd-25a67a48ce18)
May I ask how to calculate F1MO or how to solve it?

**Comment by marmoi** [comment]
Hi,
F1MO is the value return by the function _get_threshold_independent_  called: f_best['macro_average'].
